# Generated by Django 2.2 on 2021-11-09 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0003_auto_20211109_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='user_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
