# Generated by Django 2.2 on 2021-11-19 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0005_donate_is_expired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donate',
            name='is_expired',
        ),
    ]
