# Generated by Django 2.2 on 2021-11-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_auto_20211107_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='img',
            field=models.ImageField(default='', upload_to='photos/animals'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='profile_img',
            field=models.ImageField(default='', upload_to='photos/animals'),
        ),
    ]
