# Generated by Django 2.2 on 2021-11-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_auto_20211107_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='details',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='animal',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
