# Generated by Django 2.2 on 2021-11-03 02:23

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_auto_20211103_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='img',
            field=models.FileField(default='', storage=django.core.files.storage.FileSystemStorage(location='/media/photos'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='animal',
            name='profile_img',
            field=models.FileField(default='', storage=django.core.files.storage.FileSystemStorage(location='/media/photos'), upload_to=''),
        ),
    ]
