# Generated by Django 2.2 on 2021-11-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='img',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
