# Generated by Django 2.2 on 2021-11-03 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20211103_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='img',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
