# Generated by Django 2.2 on 2021-11-19 14:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20211107_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_uploaded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='img',
            field=models.ImageField(default='', upload_to='photos/news'),
        ),
    ]
