# Generated by Django 2.2 on 2021-11-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20211120_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description_normalized',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='event',
            name='title_normalized',
            field=models.CharField(default='', max_length=100),
        ),
    ]
