# Generated by Django 2.2 on 2021-11-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20211128_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description_normalized',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='event',
            name='title_normalized',
            field=models.CharField(max_length=100),
        ),
    ]
