# Generated by Django 2.2 on 2021-11-03 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
