# Generated by Django 2.2 on 2021-11-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211107_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='', upload_to='photos/user'),
        ),
    ]
