# Generated by Django 2.2 on 2021-11-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211113_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='photos/animals/rabbit.jpeg', upload_to='photos/user'),
        ),
    ]
