# Generated by Django 2.2 on 2021-11-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20211129_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='photos/user/default-avatar.png', upload_to='photos/user'),
        ),
    ]
