# Generated by Django 2.2 on 2021-11-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_auto_20211113_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
